# Generated by Django 3.0 on 2025-01-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_comments_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
